// PostgreSQL model metadata. Scalar fields are real columns; embedded snapshots use JSONB.
// Schema changes also require a versioned SQL migration.
module.exports = {
    BankAccount: {
        table: "bankaccounts",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            bankName: {"type":"text","required":true},
            accountNumber: {"type":"text","required":true},
            accountHolder: {"type":"text","default":""},
            openingBalance: {"type":"number","default":0},
            currentBalance: {"type":"number","default":0},
            accountType: {"type":"text","enum":["checking","savings","business"],"default":"business"},
            isActive: {"type":"boolean","default":true},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["storeId"],"unique":false}],
    },
    BankTransaction: {
        table: "banktransactions",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            accountId: {"type":"id","required":true,"ref":"BankAccount"},
            type: {"type":"text","required":true,"enum":["deposit","withdrawal","transfer_out","transfer_in"]},
            amount: {"type":"number","required":true},
            balanceAfter: {"type":"number","required":true},
            description: {"type":"text","default":""},
            reference: {"type":"text","default":""},
            date: {"type":"date","required":true},
            createdBy: {"type":"id","ref":"User"},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["accountId"],"unique":false},{"fields":["accountId","date"],"unique":false}],
    },
    Category: {
        table: "categories",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            name: {"type":"text","required":true},
            description: {"type":"text","default":""},
            isActive: {"type":"boolean","default":true},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["name","storeId"],"unique":true}],
    },
    Customer: {
        table: "customers",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            name: {"type":"text","required":true},
            phone: {"type":"text","default":""},
            email: {"type":"text","default":""},
            loyaltyCard: {"type":"text","default":null},
            creditLimit: {"type":"number","default":0},
            creditBalance: {"type":"number","default":0},
            walletBalance: {"type":"number","default":0},
            loyaltyPoints: {"type":"number","default":0},
            isActive: {"type":"boolean","default":true},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["storeId"],"unique":false},{"fields":["phone","storeId"],"unique":false},{"fields":["loyaltyCard"],"unique":false}],
    },
    Expense: {
        table: "expenses",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            expenseTypeId: {"type":"id","required":true,"ref":"ExpenseType"},
            amount: {"type":"number","required":true},
            description: {"type":"text","default":""},
            date: {"type":"date","required":true},
            paymentMethod: {"type":"text","enum":["cash","bank","mobile"],"default":"cash"},
            reference: {"type":"text","default":""},
            createdBy: {"type":"id","ref":"User"},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["storeId","date"],"unique":false},{"fields":["expenseTypeId"],"unique":false}],
    },
    ExpenseType: {
        table: "expensetypes",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            name: {"type":"text","required":true},
            description: {"type":"text","default":""},
            isActive: {"type":"boolean","default":true},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["name","storeId"],"unique":true}],
    },
    LoyaltyTransaction: {
        table: "loyaltytransactions",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            customerId: {"type":"id","required":true,"ref":"Customer"},
            points: {"type":"number","required":true},
            type: {"type":"text","required":true,"enum":["earn","redeem","adjustment"]},
            orderId: {"type":"id","ref":"Order","default":null},
            description: {"type":"text","default":""},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["customerId"],"unique":false},{"fields":["customerId","createdAt"],"unique":false}],
    },
    Order: {
        table: "orders",
        fields: {
            profit: {"type":"number","default":0},
            qrExpiresAt: {"type":"date"},
            orderNumber: {"type":"text","required":true},
            storeId: {"type":"id","required":true,"ref":"Store"},
            cashierId: {"type":"id","required":true,"ref":"User"},
            customerId: {"type":"id","ref":"Customer","default":null},
            items: {"type":"json","default":[],"items":{"productId":{"type":"id","required":true,"ref":"Product"},"productName":{"type":"text"},"quantity":{"type":"number","required":true},"unitPrice":{"type":"number","required":true},"total":{"type":"number","required":true}}},
            subtotal: {"type":"number","required":true},
            discount: {"type":"number","default":0},
            discountType: {"type":"text","enum":["flat","percent"],"default":"flat"},
            tax: {"type":"number","default":0},
            costTotal: {"type":"number","default":0},
            total: {"type":"number","required":true},
            paymentMethod: {"type":"text","enum":["cash","card","mobile","credit","wallet","mixed"],"default":"cash"},
            status: {"type":"text","enum":["completed","pending","cancelled"],"default":"completed"},
            qrToken: {"type":"text","default":null},
            voucherId: {"type":"id","ref":"Voucher","default":null},
            shiftId: {"type":"id","ref":"Shift","default":null},
            notes: {"type":"text"},
        },
        indexes: [{"fields":["orderNumber"],"unique":false},{"fields":["storeId"],"unique":false},{"fields":["createdAt","storeId"],"unique":false},{"fields":["cashierId","createdAt"],"unique":false},{"fields":["orderNumber"],"unique":true}],
        number: ["orderNumber","ORD"],
    },
    Payroll: {
        table: "payrolls",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            userId: {"type":"id","required":true,"ref":"User"},
            month: {"type":"number","required":true},
            year: {"type":"number","required":true},
            basicSalary: {"type":"number","required":true},
            bonus: {"type":"number","default":0},
            deductions: {"type":"number","default":0},
            netSalary: {"type":"number","required":true},
            paymentMethod: {"type":"text","enum":["cash","bank","mobile"],"default":"cash"},
            status: {"type":"text","enum":["draft","pending","paid"],"default":"draft"},
            paidDate: {"type":"date","default":null},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["userId","month","year","storeId"],"unique":true}],
    },
    Plan: {
        table: "plans",
        fields: {
            name: {"type":"text","enum":["basic","standard","pro"],"required":true},
            features: {"type":"json","default":[]},
            price: {"type":"number","default":0},
            trialDays: {"type":"number","default":7},
            limits: {"type":"json","default":{"users":2,"products":500,"branches":1}},
        },
        indexes: [{"fields":["name"],"unique":true}],
    },
    Product: {
        table: "products",
        fields: {
            categoryId: {"type":"id","ref":"Category","default":null},
            supplierId: {"type":"id","ref":"Supplier","default":null},
            barcode: {"type":"text","required":true},
            name: {"type":"text","required":true},
            category: {"type":"text","default":"General"},
            costPrice: {"type":"number","required":true,"select":false},
            sellingPrice: {"type":"number","required":true},
            stock: {"type":"number","required":true,"default":0},
            lowStockAlert: {"type":"number","default":10},
            unit: {"type":"text","enum":["pcs","kg","liter","ltr","dozen","pack","meter","box","carton"],"default":"pcs"},
            storeId: {"type":"id","required":true,"ref":"Store"},
            description: {"type":"text","default":""},
            isActive: {"type":"boolean","default":true},
        },
        indexes: [{"fields":["barcode"],"unique":false},{"fields":["storeId"],"unique":false},{"fields":["barcode","storeId"],"unique":true}],
    },
    Purchase: {
        table: "purchases",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            purchaseNumber: {"type":"text","required":true},
            supplierId: {"type":"id","required":true,"ref":"Supplier"},
            items: {"type":"json","default":[],"items":{"productId":{"type":"id","required":true,"ref":"Product"},"productName":{"type":"text"},"quantity":{"type":"number","required":true},"costPrice":{"type":"number","required":true},"total":{"type":"number","required":true}}},
            subtotal: {"type":"number","required":true},
            discount: {"type":"number","default":0},
            tax: {"type":"number","default":0},
            total: {"type":"number","required":true},
            balanceDue: {"type":"number","required":true},
            paidAmount: {"type":"number","default":0},
            status: {"type":"text","enum":["pending","partial","paid"],"default":"pending"},
            createdBy: {"type":"id","ref":"User"},
            notes: {"type":"text"},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["purchaseNumber"],"unique":false},{"fields":["storeId","createdAt"],"unique":false},{"fields":["supplierId","status"],"unique":false},{"fields":["purchaseNumber"],"unique":true}],
        number: ["purchaseNumber","PUR"],
    },
    PurchaseReturn: {
        table: "purchasereturns",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            returnNumber: {"type":"text","required":true},
            purchaseId: {"type":"id","required":true,"ref":"Purchase"},
            supplierId: {"type":"id","required":true,"ref":"Supplier"},
            items: {"type":"json","default":[],"items":{"productId":{"type":"id","required":true,"ref":"Product"},"productName":{"type":"text"},"quantity":{"type":"number","required":true},"costPrice":{"type":"number","required":true},"total":{"type":"number","required":true}}},
            totalAmount: {"type":"number","required":true},
            reason: {"type":"text","default":""},
            createdBy: {"type":"id","ref":"User"},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["returnNumber"],"unique":false},{"fields":["storeId","createdAt"],"unique":false},{"fields":["returnNumber"],"unique":true}],
        number: ["returnNumber","PRN"],
    },
    Quotation: {
        table: "quotations",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            quotationNumber: {"type":"text","required":true},
            customerName: {"type":"text","required":true},
            customerId: {"type":"id","ref":"Customer","default":null},
            items: {"type":"json","default":[],"items":{"productId":{"type":"id","required":true,"ref":"Product"},"productName":{"type":"text"},"quantity":{"type":"number","required":true},"unitPrice":{"type":"number","required":true},"discount":{"type":"number","default":0},"total":{"type":"number","required":true}}},
            subtotal: {"type":"number","required":true},
            discount: {"type":"number","default":0},
            tax: {"type":"number","default":0},
            total: {"type":"number","required":true},
            validUntil: {"type":"date","required":true},
            status: {"type":"text","enum":["draft","sent","accepted","rejected","expired"],"default":"draft"},
            convertedToOrderId: {"type":"id","ref":"Order","default":null},
            createdBy: {"type":"id","ref":"User"},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["quotationNumber"],"unique":false},{"fields":["storeId","status"],"unique":false},{"fields":["quotationNumber"],"unique":true}],
        number: ["quotationNumber","QUO"],
    },
    Salesman: {
        table: "salesmen",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            name: {"type":"text","required":true},
            phone: {"type":"text","default":""},
            email: {"type":"text","default":""},
            commissionRate: {"type":"number","default":5},
            isActive: {"type":"boolean","default":true},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["storeId"],"unique":false}],
    },
    SalesReturn: {
        table: "salesreturns",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            returnNumber: {"type":"text","required":true},
            orderId: {"type":"id","ref":"Order","default":null},
            customerId: {"type":"id","ref":"Customer","default":null},
            items: {"type":"json","default":[],"items":{"productId":{"type":"id","required":true,"ref":"Product"},"productName":{"type":"text"},"quantity":{"type":"number","required":true},"unitPrice":{"type":"number","required":true},"total":{"type":"number","required":true}}},
            totalAmount: {"type":"number","required":true},
            refundMethod: {"type":"text","enum":["cash","wallet","loyalty_points"],"default":"cash"},
            createdBy: {"type":"id","ref":"User"},
            notes: {"type":"text"},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["returnNumber"],"unique":false},{"fields":["storeId","createdAt"],"unique":false},{"fields":["returnNumber"],"unique":true}],
        number: ["returnNumber","SRN"],
    },
    Shift: {
        table: "shifts",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            cashierId: {"type":"id","required":true,"ref":"User"},
            openedAt: {"type":"date","required":true},
            closedAt: {"type":"date","default":null},
            openingCash: {"type":"number","required":true},
            closingCash: {"type":"number","default":null},
            expectedCash: {"type":"number","default":null},
            cashDifference: {"type":"number","default":null},
            status: {"type":"text","enum":["open","closed"],"default":"open"},
            notes: {"type":"text","default":""},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["cashierId","status"],"unique":false},{"fields":["createdAt","storeId"],"unique":false}],
    },
    StockLog: {
        table: "stocklogs",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            productId: {"type":"id","required":true,"ref":"Product"},
            delta: {"type":"number","required":true},
            reason: {"type":"text","required":true,"enum":["sale","restock","return","damage","manual_adjustment","transfer_out","transfer_in"]},
            changedBy: {"type":"id","required":true,"ref":"User"},
            orderId: {"type":"id","ref":"Order","default":null},
            purchaseId: {"type":"id","ref":"Purchase","default":null},
            note: {"type":"text","default":""},
            newBalance: {"type":"number","required":true},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["productId"],"unique":false},{"fields":["createdAt","storeId"],"unique":false},{"fields":["productId","storeId"],"unique":false}],
    },
    StockTransfer: {
        table: "stocktransfers",
        fields: {
            fromStoreId: {"type":"id","required":true,"ref":"Store"},
            toStoreId: {"type":"id","required":true,"ref":"Store"},
            transferNumber: {"type":"text","required":true},
            items: {"type":"json","default":[],"items":{"productId":{"type":"id","required":true,"ref":"Product"},"productName":{"type":"text"},"quantity":{"type":"number","required":true}}},
            status: {"type":"text","enum":["pending","in_transit","received","cancelled"],"default":"pending"},
            initiatedBy: {"type":"id","required":true,"ref":"User"},
            receivedBy: {"type":"id","ref":"User","default":null},
            notes: {"type":"text","default":""},
        },
        indexes: [{"fields":["fromStoreId"],"unique":false},{"fields":["toStoreId"],"unique":false},{"fields":["transferNumber"],"unique":false},{"fields":["fromStoreId","status"],"unique":false},{"fields":["toStoreId","status"],"unique":false},{"fields":["transferNumber"],"unique":true}],
        number: ["transferNumber","STR"],
    },
    Store: {
        table: "stores",
        fields: {
            tenantId: {"type":"id","required":true,"ref":"Tenant"},
            name: {"type":"text","required":true},
            address: {"type":"text","default":""},
            phone: {"type":"text","default":""},
            taxRate: {"type":"number","default":5},
            taxLabel: {"type":"text","default":"VAT"},
            currency: {"type":"text","default":"USD"},
            timezone: {"type":"text","default":"UTC"},
            receiptFooter: {"type":"text","default":"Thank you for your purchase!"},
            logo: {"type":"text","default":null},
            isActive: {"type":"boolean","default":true},
        },
        indexes: [{"fields":["tenantId"],"unique":false},{"fields":["tenantId"],"unique":false}],
    },
    SubscriptionLog: {
        table: "subscriptionlogs",
        fields: {
            tenantId: {"type":"id","required":true,"ref":"Tenant"},
            plan: {"type":"text","required":true},
            amount: {"type":"number","required":true},
            currency: {"type":"text","default":"USD"},
            paidAt: {"type":"date","default":"now"},
            periodStart: {"type":"date","required":true},
            periodEnd: {"type":"date","required":true},
            method: {"type":"text","enum":["stripe","paypal","manual","trial"],"default":"manual"},
            status: {"type":"text","enum":["paid","failed","refunded"],"default":"paid"},
            transactionId: {"type":"text","default":null},
        },
        indexes: [{"fields":["tenantId"],"unique":false},{"fields":["tenantId","createdAt"],"unique":false}],
    },
    Supplier: {
        table: "suppliers",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            name: {"type":"text","required":true},
            company: {"type":"text","default":""},
            phone: {"type":"text","default":""},
            email: {"type":"text","default":""},
            address: {"type":"text","default":""},
            openingBalance: {"type":"number","default":0},
            currentBalance: {"type":"number","default":0},
            isActive: {"type":"boolean","default":true},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["storeId"],"unique":false},{"fields":["phone","storeId"],"unique":false}],
    },
    Tenant: {
        table: "tenants",
        fields: {
            businessName: {"type":"text","required":true},
            ownerEmail: {"type":"text","required":true,"lowercase":true},
            plan: {"type":"text","enum":["basic","standard","pro"],"default":"basic"},
            subscriptionStatus: {"type":"text","enum":["active","expired","suspended"],"default":"active"},
            expireAt: {"type":"date","required":true},
            isActive: {"type":"boolean","default":true},
            isSetupComplete: {"type":"boolean","default":false},
            language: {"type":"text","enum":["en","ar","bn"],"default":"en"},
            currency: {"type":"text","default":"USD"},
        },
        indexes: [{"fields":["ownerEmail"],"unique":true},{"fields":["ownerEmail"],"unique":false},{"fields":["subscriptionStatus"],"unique":false}],
    },
    User: {
        table: "users",
        fields: {
            name: {"type":"text","required":true},
            email: {"type":"text","required":true,"lowercase":true},
            password: {"type":"text","required":true,"select":false},
            role: {"type":"text","enum":["owner","manager","cashier"],"default":"cashier"},
            tenantId: {"type":"id","required":true,"ref":"Tenant"},
            isActive: {"type":"boolean","default":true},
            lastLogin: {"type":"date","default":null},
        },
        indexes: [{"fields":["email"],"unique":false},{"fields":["tenantId"],"unique":false},{"fields":["email","tenantId"],"unique":true}],
    },
    Voucher: {
        table: "vouchers",
        fields: {
            storeId: {"type":"id","required":true,"ref":"Store"},
            code: {"type":"text","required":true,"uppercase":true},
            type: {"type":"text","required":true,"enum":["flat","percent"]},
            value: {"type":"number","required":true},
            usageLimit: {"type":"number","default":null},
            usageCount: {"type":"number","default":0},
            validFrom: {"type":"date","required":true},
            validUntil: {"type":"date","required":true},
            minOrderValue: {"type":"number","default":0},
            maxDiscount: {"type":"number","default":null},
            customerId: {"type":"id","ref":"Customer","default":null},
            isActive: {"type":"boolean","default":true},
        },
        indexes: [{"fields":["storeId"],"unique":false},{"fields":["code"],"unique":true},{"fields":["storeId","code"],"unique":false}],
    },
};
